# gbolo/vsummary linter settings. Basic for now...

run:
  concurrency: 2
  deadline: 1m
  issues-exit-code: 1
  tests: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  golint:
    min-confidence: 0
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - gosec
    - misspell
    - unused
    - deadcode
    - varcheck
    # - errcheck
    # - maligned
    # - gosimple
    # - golint

run:
  skip-dirs:
    - testdata
    - contrib
    - www
    - vendor

issues:
  exclude-rules:
    # we only construct some questionable sql queries in the datatables pkg
    # IGNORE it for now...
    - text: "G201: SQL string formatting"
      linters:
        - gosec
