language: go

go:
  - 1.12.x

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends build-essential make

script:
  - make versions
  - make lint
  - make unit-test
  - make setup-integration-prereqs
  - make integration-test
  - make down-integration-prereqs
  - make all
  - make docker
